### ISSUE TITLE
Duckie's v0.3.0 ToDo List

### ISSUE THREAD

**Issue by SkiHatDuckie** [SkiHatDuckie/birds-eye#10]
### External Tool:
- [x] Add an options menu.
- [x] Add logging as an option. This is to help with debugging the external tool and diagnosing other socket related nonsense.
- [x] Redesign external tool and python library to work in a blocking fashion when commandeer mode is enabled. The external tool will block on every frame for input from a python script.
- [x] Create a timeout for how long the external tool should wait for input before skipping to the next frame.
- [x] Send the frame-count when sending data to a python script.
- [x] Add option for changing how long the external tool should wait for input.
- [x] Refactor external tool code / General cleanup.
- [x] Improve on messages displayed in the external tool GUI (make `_lblError` more useful to the user).
### Library:
- [x] Reorganize python library.
- [x] Add a function for returning the latest frame-count received from the external tool.
- [x] Add functions for enabling/disabling commandeer mode from the python script.
### Other Project Tasks:
- [x] Create online documentation for setup and usage of the birds-eye library and external tool.
