### ISSUE TITLE
Duckie's v0.3.1 ToDo List

### ISSUE THREAD

**Issue by SkiHatDuckie** [SkiHatDuckie/birds-eye#14]
### External Tool:
- [x] The tool, in some situations, is unable (or doesn't check) to determine when a python client has ceased functioning. This needs to be investigated further.
### Library:
- [x] Fix address list storage in `birdseye.Memory.address_list`.
- [x] Thoroughly test `birdseye.Memory` for any other bugs.
### Other Project Tasks:
- [x] The homepage link on the PyPi page is incorrect.
- [x] Add a Getting Started menu to the ReadTheDocs page.
- [x] Add examples to the ReadTheDocs page.
- [x] Get rid of any bad links within ReadTheDocs page.
