### ISSUE TITLE
Duckie's v0.2.1 ToDo List

### ISSUE THREAD

**Issue by SkiHatDuckie** [SkiHatDuckie/birds-eye#6]
##  v0.2.1 ToDo List:

- [x] fix documentation in `add_address_range`
- [x] in `get_memory`, split string at every ';' before returning `self.received_memory` (return as list)
- [x] initialize `self.received_memory` to an empty string, instead of NoneType
- [x] set `self.received_memory` to format described in `get_memory`'s documentation, when no memory has been received
- [x] add a clear approach for reconnecting after connection is prematurely lost (python end)
- [x] add way to gracefully close connection (both ends)
- [x] fix socket resources not properly being disposed of when external tool is closed
- [x] hunt down any other spelling/grammar errors in documentation

Additional issues created by me or others may be added to this release.
